NEW CsvBulkLoader integration
silverstripe/silverstripe-versioned-snapshots pull request #45
Opened 2021-05-13 21:04 UTC by chillu

New snapshot for every row that's actually been created or changed.
Ideally we'd use createSnapshotEvent('CSV Import from <file>', [$objs]),
but that can be very resource intensive on bulk imports (PHP memory).
The bulk loader destroys the DataObject instances after loading them,
so we'd need to recreate them.

We could allow createSnapshot() to accept a map of "class => ID"
instead, and then recreate+destroy the DataObject instances on the fly.
For now, recording one snapshot per row is good enough.

Relies on https://github.com/silverstripe/silverstripe-framework/pull/9929

2021-05-13 23:41 UTC, unclecheese requested changes
It's really too bad we can't find a way to use `SnapshotEvent` here, because that was the intended purpose of that API. All we're really trying to do here is provide a timestamp for significant change to the content. 

If you look at things like the CMSMain handler, we add snapshots that contain only the event itself as the origin, e.g. "reorder site tree".

Problem is, we don't show those snapshots anywhere. If you reorder the site tree right now, there's a record of it happening in the snapshots table, but the admin doesn't show it because it's not related to any specific content type. Other events like "reorder elements" do show, because we relate them directly to an elemental area.

Seems like a bug... ?? This to me should follow the same pattern as reordering the site tree. Here's a generic thing that happened at this date and time. 

I'll check in with the TFs on this one to see how they're dealing with snapshot events. They use them a lot for bulk translation imports and other things like this.

2021-05-13 23:41 UTC, unclecheese commented on src/CsvBulkLoader/SaveListener.php
> +            Event::create('import', ['obj' => $obj])
This `Event` object is a bit weird, with this `action` parameter as you probably discovered. The idea here is that you can do filtering at the configuration level by specifying the "action" as a certain context you want to bind to. It makes sense with things like "graphqlMutation.updateFile" or "cmsAction.reorderTree", but for things like this it's not so clear.

What I'd probably do here is pass `get_class($obj)` as the action. That way you could conceivably do `on: 'csvBulkLoaderImport.SilverStripe\CMS\Model\SiteTree` to only bind to page imports, for instance.

Let's also call it "record" for consistency with other event handlers.

```suggestion
            Event::create(get_class($obj), ['record' => $obj])
```

2021-05-13 23:41 UTC, unclecheese commented on src/Handler/CsvBulkLoader/Handler.php
> +        $obj = $context->get('obj');
```suggestion
        $obj = $context->get('record');
```

2021-05-13 23:41 UTC, unclecheese commented on src/Handler/CsvBulkLoader/Handler.php
> +            throw new \InvalidArgumentException('Requires "obj" in context');
```suggestion
            throw new \InvalidArgumentException('Requires "record" in context');
```

2021-05-17 20:09 UTC, chillu commented
Thanks for reviewing, I'm happy with the `record` rename. I reckon these kind of batch updates are reasonably rare that it's a low priority to solve this on a `SnapshotEvent` API level right now.

2021-05-18 04:22 UTC, merged